### ISSUE TITLE
TAF 'Hash' and 'Audio-Size' is missing in new-web

### ISSUE THREAD

**Issue by oliver-koch** [toniebox-reverse-engineering/teddycloud_web#106]
I want to contribute a missing tonie to the tonies-json repo.
For this, 'audio-id', 'audio-size' and 'hash' needs to be added. 

Before version 0.6.0 i could extract this data from old-web very easiely.
with with teddy-cloud 0.6.0 only new-web is available, which does not provide the usefull data.

information could be added e.g. in library view in own colums, which are not visable by default and be enabled.

**Comment by henryk86** [comment]
it's available in content and library. just double click on a row.

**Comment by henryk86** [comment]
its not shown in the table directly as there is no space for it

**Comment by henryk86** [comment]
![image](https://github.com/user-attachments/assets/e3c33040-ebe9-49c9-bcfb-5c709a307577)

**Comment by oliver-koch** [comment]
ah shit, i searched for it, but did not find it... very cool. works for me. i will close the issue.
thank you very much!

**Comment by oliver-koch** [comment]
closed. already implemented
