### ISSUE TITLE
Add page for missing translation strings

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#127]
It may be helpful to have a page that shows missing translation-strings, like the one with the missing tonie information.

**Comment by henryk86** [comment]
not sure if this is something for the frontend. 

As far as a know, you can show the missing translations if you were on a page where such missing translation appears, so if you do not visit every page in every variation, you will not get all missing translation strings.

another solution would be maintaining another file, which stores all translation keys and compare it to the actual ones. Also not really handy...

For now comparing the number of lines gives a good hint if something is missing (even there are currently some differences between all files in size of 1 line)

**Comment by SciLor** [comment]
The idea I have in mind would be: Expect the English translation is complete and compare it with the other ones, including non used strings.

**Comment by henryk86** [comment]
ok. then chatGPT proposes a solution. will test that:

To implement this translation comparison logic within a React page, you can use a similar approach as the script I described but move the logic into a React component. This component can display the missing and extra keys in the browser.

Here’s a step-by-step guide on how to create a React page that compares the translation JSON files and shows missing and extra keys dynamically:

Step 1: Organize Your Translation Files
Assume your translation files are stored locally in the public folder, like this:

public/
├── translations/
│   ├── en.json
│   ├── fr.json
│   ├── de.json
│   ├── es.json

These will be fetched dynamically within the React app.

Step 2: Create the React Component
Here’s a React component that fetches the translation files, compares them, and displays missing and extra keys for each language.

```jsx
import React, { useEffect, useState } from 'react';

// Recursive function to find missing keys
const findMissingKeys = (baseObj, otherObj, parentKey = '') => {
  const missingKeys = [];
  Object.keys(baseObj).forEach((key) => {
    const fullKey = parentKey ? `${parentKey}.${key}` : key;
    if (typeof baseObj[key] === 'object' && !Array.isArray(baseObj[key])) {
      missingKeys.push(...findMissingKeys(baseObj[key], otherObj[key] || {}, fullKey));
    } else if (!(key in otherObj)) {
      missingKeys.push(fullKey);
    }
  });
  return missingKeys;
};

// Recursive function to find extra keys
const findExtraKeys = (baseObj, otherObj, parentKey = '') => {
  const extraKeys = [];
  Object.keys(otherObj).forEach((key) => {
    const fullKey = parentKey ? `${parentKey}.${key}` : key;
    if (typeof otherObj[key] === 'object' && !Array.isArray(otherObj[key])) {
      extraKeys.push(...findExtraKeys(baseObj[key] || {}, otherObj[key], fullKey));
    } else if (!(key in baseObj)) {
      extraKeys.push(fullKey);
    }
  });
  return extraKeys;
};

const TranslationComparison = () => {
  const [translations, setTranslations] = useState({});
  const [missingKeys, setMissingKeys] = useState({});
  const [extraKeys, setExtraKeys] = useState({});
  const [loading, setLoading] = useState(true);

  const languages = ['en', 'fr', 'de', 'es']; // Add other languages as needed
  const baseLang = 'en'; // Base language to compare against

  useEffect(() => {
    // Fetch all translation files
    const fetchTranslations = async () => {
      const fetchedTranslations = {};
      for (let lang of languages) {
        const response = await fetch(`/translations/${lang}.json`);
        const data = await response.json();
        fetchedTranslations[lang] = data;
      }
      setTranslations(fetchedTranslations);
      setLoading(false);
    };
    fetchTranslations();
  }, []);

  useEffect(() => {
    if (!loading && translations[baseLang]) {
      const baseTranslations = translations[baseLang];
      const missing = {};
      const extra = {};

      // Compare each language against the base language
      languages.forEach((lang) => {
        if (lang !== baseLang) {
          const otherTranslations = translations[lang];
          missing[lang] = findMissingKeys(baseTranslations, otherTranslations);
          extra[lang] = findExtraKeys(baseTranslations, otherTranslations);
        }
      });

      setMissingKeys(missing);
      setExtraKeys(extra);
    }
  }, [loading, translations]);

  if (loading) return <p>Loading translations...</p>;

  return (
    <div>
      <h1>Translation Comparison</h1>

      {languages.map((lang) => (
        lang !== baseLang && (
          <div key={lang}>
            <h2>Language: {lang.toUpperCase()}</h2>

            <h3>Missing Keys:</h3>
            {missingKeys[lang]?.length > 0 ? (
              <ul>
                {missingKeys[lang].map((key, index) => (
                  <li key={index}>{key}</li>
                ))}
              </ul>
            ) : (
              <p>No missing keys.</p>
            )}

            <h3>Extra Keys:</h3>
            {extraKeys[lang]?.length > 0 ? (
              <ul>
                {extraKeys[lang].map((key, index) => (
                  <li key={index}>{key}</li>
                ))}
              </ul>
            ) : (
              <p>No extra keys.</p>
            )}
          </div>
        )
      ))}
    </div>
  );
};

export default TranslationComparison;
```

Step 3: Explanation
Fetching the JSON files:

In the useEffect hook, the component fetches the translation files for each language from the /locales folder using fetch.
These are stored in the translations state object, where each language's translations are keyed by the language code (e.g., en, fr, de).
Comparing translations:

Once all the translation files are fetched, the code compares the translations using the recursive findMissingKeys and findExtraKeys functions.
It compares each language’s translation against the base language (English, in this case) and stores the missing and extra keys in the missingKeys and extraKeys state objects.
Displaying results:

For each language other than the base language, the component displays the list of missing and extra keys. If no missing or extra keys are found, a message like "No missing keys" or "No extra keys" is shown.
Step 4: Styling and Routing (Optional)
If you want to add this page to your app's navigation, you can include it in your App.js or routes configuration like this:

```jsx
import React from 'react';
import { BrowserRouter as Router, Route, Routes } from 'react-router-dom';
import TranslationComparison from './TranslationComparison';

function App() {
  return (
    <Router>
      <Routes>
        <Route path="/translation-comparison" element={<TranslationComparison />} />
        {/* Other routes */}
      </Routes>
    </Router>
  );
}

export default App;
```

Step 5: Testing
Ensure your translation files (en.json, fr.json, de.json, etc.) are located in the public/translations/ folder.
Visit the /translation-comparison page in your app to see the missing and extra keys for each language compared to the base language.
Conclusion
This React page dynamically loads and compares the translation files, showing any missing or extra keys for each language. You can expand it to support more languages, improve the styling, or add features like exporting the results to a file.

Let me know if you need any additional details!
