### ISSUE TITLE
Combine flashing page into one with a selection for the box type + open the box

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#128]
As a first step users need to open their box. 
- Add a short tutorial how to open the box and identify the chip
- To select the box type, having images of each main chip (CC3200/CC3235/ESP32) as a link to the flashing page

![image](https://github.com/user-attachments/assets/f5e641d5-ece8-4272-997e-2aaad3a3ab4b)

**Comment by henryk86** [comment]
So I will restructure that. New main entry setup toniebox for tc. There a rough step overview. New sub page open the box and identify the version and link to the corresponding box version guide. Then the current pages as other subpages.

tonieboxes
 - tonieboxes
 - Setup Toniebox for TeddyCloud
    - open box and identify version
    - Esp32
    - Cc3200
    - Cc3235
    - alturl.305.json patch

**Comment by henryk86** [comment]
this ticket is solved i think. there will be still separated pages, but the idea is implemented ;)
