### ISSUE TITLE
[Devmode only] Reloading content browser loses directory

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#132]
If I am reloading the browser with following url:
`/web/tonies/content?path=/02410214`
it won't open the same directory again but go to the root, losing the path component.

**Comment by henryk86** [comment]
That should actually work in production mode. (Not in dev mode, vite sucks there)

**Comment by henryk86** [comment]
just rechecked it in dev mode. the directory stays at it is. can you also recheck?

**Comment by henryk86** [comment]
rechecked again, can not reproduce this wether in prod version nor in current dev version
