### ISSUE TITLE
View Toniebox not loading

### ISSUE THREAD

**Issue by rgoggy** [toniebox-reverse-engineering/teddycloud_web#133]
When trying to load the view Tonieboxen I get an error in the Chrome Log
"index-hMb_Kd2P.js:610 Error fetching and transforming data: TypeError: (intermediate value) is not iterable
    at n (index-hMb_Kd2P.js:610:9957)"
In the browser it just shows Loading.

The view Tonies is working and shows all Tonies

**Comment by henryk86** [comment]
Can you check your tonieboxes.custom.json?

Exists this file? If so, is it empty? If so, please add [] as content and restart teddycloud.

**Comment by rgoggy** [comment]
> Can you check your tonieboxes.custom.json?
> 
> Exists this file? If so, is it empty? If so, please add [] as content and restart teddycloud.

It exists with following Content 

{
	"live":	false,
	"nocloud":	false,
	"source":	"",
	"skip_seconds":	0,
	"cache":	false,
	"cloud_ruid":	"",
	"cloud_auth":	"",
	"cloud_override":	false,
	"tonie_model":	"",
	"hide":	false,
	"claimed":	false,
	"_version":	5
}

**Comment by rgoggy** [comment]
I created a new Toniebox.custom.json with just [] and now it loaded
