### ISSUE TITLE
[Encoding] If encoding fails, show error

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#135]
If the encoding fails with a 502 for example, the encoding page stays on encoding.

**Comment by henryk86** [comment]
Which encoding? The drag and drop audio encoder or the filebrowser encoding?

**Comment by SciLor** [comment]
The drag and drop encoding, PCM upload fails.

**Comment by henryk86** [comment]
@SciLor : fixed in develop
