### ISSUE TITLE
Audioplayer doubled?

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud_web#14]
It looks like the audioplayer is doubled:

![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/7e2b23bb-06a0-46e4-a2a0-7046e7609c4a)

or better: a white compact audioplayer is placed right within the dark audio player.

Shall it be so or is it a bug? or Shall one version be displayed on desktopn, one in mobile?

**Comment by SciLor** [comment]
The right one is there for development purposes as the custom one is missing mute /volume.

**Comment by holgerb** [comment]
There is also an issue related to the used media session within this component. 
cf. https://github.com/toniebox-reverse-engineering/teddycloud_web/pull/1#issue-2223646240

I had not time recently to work it sadly...

**Comment by henryk86** [comment]
overworked in gh-72:
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/a39a1774-eed9-41af-bf4a-f989fe4bbc59)
