### ISSUE TITLE
Add info instead of No-Data if no tonieboxes are available

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#154]
To make it more clear how to add a box and when a box is in the toniebox view, instead of no data there should be a hint that boxes only occur after a successful connection.

![image](https://github.com/user-attachments/assets/d90fe199-66b8-47c4-8de3-9a53c9d891ec)

**Comment by henryk86** [comment]
added custom no data message:

![{4170DCFF-035B-40FE-BAF0-B34CC6EB71CC}](https://github.com/user-attachments/assets/62c1b094-de41-4636-8326-7cab2b0dcfec)
