### ISSUE TITLE
Question: Difference DEV and build Version

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud_web#17]
In DEV Mode (local Server) there are some minor differences to the build version.

E.g. the h1 element on homepage is bigger in DEV mode (2em) than in the build version (1em). In both cases the size definition seems to come from the user agent. That’s weird. 

Also image assets are not shown correctly in DEV mode, is there any special setting nesessary ? I assume the static image folder is not correct linked in DEV mode.

**Comment by SciLor** [comment]
I possible problem could be that CORS isn't set to * within teddyCloud

**Comment by henryk86** [comment]
I use a chrome extension with enables Corse. Without that nothing works. But I will have a look.

**Comment by SciLor** [comment]
> I use a chrome extension with enables Corse. Without that nothing works. But I will have a look.

No need for the extension, there is an option within teddyCloud

**Comment by henryk86** [comment]
changed teddycloud Cors option to *, no change.

as the not shown images are the ones which are NOT loaded (or fetched url of them) from teddycloud, i think there is no link to CORS.

<img alt=" - " src="/img_unknown.png"> this element for example is not found in DEV environment

**Comment by henryk86** [comment]
(which is not included in the checked out sources...)

**Comment by SciLor** [comment]
Maybe you didn't set the host url in teddycloud?

**Comment by henryk86** [comment]
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/1a4aa893-8c17-465f-8e06-cecf6b8784f5)

**Comment by henryk86** [comment]
as the asset is not available in sources, only in "packed" version with teddycloud, i think this issue can be closed. TeddyCloud_web is no standalone app, so its ok.

the different formatting is weird, but after a restart of the DEV environment it was equal...
