### ISSUE TITLE
Create new Custom Tonie/Tag 

### ISSUE THREAD

**Issue by inonoob** [toniebox-reverse-engineering/teddycloud_web#170]
Dear all, 

### Issue: 

When trying to create a custom TAG with the "WIP: Add Model" function and tip in all info. I can see for a brief moment the needed Json entry I need to copy but then it disappears and show "Model created successful!". 

### Setup: 

- Browser Firefox 130.0.1 (64-bit)
- Browser add-on U-block & no-script disable for Teddycloud 
- OS: Linux Ubuntu 22 
- [TeddyCloud v0.6.2 (203f12d) - 2024-10-26 18:14:34 +0000 ubuntu linux-x86_64(64]
- Running on docker in a VM on proxmox

### Expected behavior: 

Show json entry to copy paste into tonies.custom.json 

-----

If I'm doing something wrong, could someone explain it ?

**Comment by henryk86** [comment]
Should be fixed in develop already

**Comment by inonoob** [comment]
@henryk86  Thank you for the feedback. I will then wait for the new version of the docker container. Thank you again for your efforts !

**Comment by henryk86** [comment]
Feel free to use the develop version ;) it’s quite stable and only if used, bugs might be found.

**Comment by inonoob** [comment]
@henryk86 ... silly me. I just changed from latest to develop and can confirm in that version it is working !

**Comment by inonoob** [comment]
Can be closed
