### ISSUE TITLE
Mobile: smaller version of Audioplayer 

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud_web#18]
Currently the Audioplayer does not fit on mobiles. 

Add a mobile optimized version of the player and

**Comment by CTeipen** [comment]
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/8715591/d3117eea-6b90-4b4c-996b-1cd6b078351f)

**Comment by henryk86** [comment]
gh-72 overworked mobile version of player (still kind of to high)
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/a5b97c63-9452-4ad5-8e05-f9f055653c5d)
