### ISSUE TITLE
Paging Tonies

### ISSUE THREAD

**Issue by CTeipen** [toniebox-reverse-engineering/teddycloud_web#24]
Für eine bessere Übersichtlichkeit der Tonies:
- Paging der Seite (bspw. 10 pro Seite anzeigen)
- Suche nach einem Tonie (RFID, Nach, etc.)
- Filtern nach Kriterien (Cloud, Spielbar, Custom, etc.)

**Comment by henryk86** [comment]
Number of tonies per page should be configurable

one small problem: the number per line depends of the screen size. Default value should fit on all screensizes that no „incomplete“ last row can happen ( grid could be adapted accordingly)

filtering should be easily extendible (if there will be labels and categories added sometimes)

**Comment by henryk86** [comment]
Paging: https://stackoverflow.com/questions/53843548/pagination-and-card-components-with-ant-design-antd

**Comment by henryk86** [comment]
started implementation. Paging added using default pagination of antd

**Comment by henryk86** [comment]
done within #29
