### ISSUE TITLE
Certificate upload box related

### ISSUE THREAD

**Issue by henryk86** [toniebox-reverse-engineering/teddycloud_web#26]
Currently you can drag & drop certificates. These files are uploaded to the default client certificate folder (I assume so). If you have multiple boxes, you might want to upload certificates for a special one. So you should be able to choose the box and use the box related client certificate path instead of the default one.

**Comment by henryk86** [comment]
@SciLor : Is this already supported by Backend?

**Comment by SciLor** [comment]
handleApiUploadCert supports the overlay parameter. So if you set the paths for the certs in the config, it should use them as target.

**Comment by henryk86** [comment]
Implemented first draft in gh-35
