### ISSUE TITLE
Check CFW on Toniebox and link to webinterface

### ISSUE THREAD

**Issue by CTeipen** [toniebox-reverse-engineering/teddycloud_web#28]
Would be nice to connect to the Toniebox being in CFW. Maybe one could save the IP of the box and add a link to the IP.

**Comment by henryk86** [comment]
you could always show a link with the ip and the web path of the cfw toniebox. problem: if you don't have CFW on your box or your box is of, the link leads to not found 404.

you could check if the box has CFW running with calling the API of CFW (e.g. https://tonies-wiki.revvox.de/docs/custom-firmware/cc3200/hackiebox-cfw/api/#box-rfid-rfid-related-commands ) and if it returns a valid responce, then show the link only. Problem: works only if the box is online...

so all in all... nothing seems to be a satisfying solution or approach. at least in my point of view

**Comment by SciLor** [comment]
Isn't it the case, that you only need a link if the CFW is started? In other cases you won't visit its webpage.
