### ISSUE TITLE
Make use of internal.last_ruid

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#30]
I may be useful to show the last_ruid that was detected on a box. It may be shown on the Toniebox overview page on each card and also on the Tonies page as a link at the top (for each box or globally?) to jump to the right tag.
The TonieCards may also have a Symbol with a mouseover indicating the box.

**Comment by henryk86** [comment]
I understand the first part - that should be easy.

the last point is not clear to me... what i understand: i have to fetch the last ruid for each box and then add some icon or what ever to the tonie which marks the tonie as "i was the last one played on box: <ul><li> Box </li></ul>"? As the same tonie could be the last on everybox someone owns?

**Comment by SciLor** [comment]
Exactly what I had in mind.

**Comment by henryk86** [comment]
There is currently no way to fetch a tonie by filtering with the ruid? I have to get all and then filter the result?

**Comment by SciLor** [comment]
No, the backend has no filtering capabilities for that.
Get all and filter on the frontend.

**Comment by henryk86** [comment]
Tonieboxmgmt:

![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/aab8fdf3-3a28-4748-a337-bd7da48ca794)

**Comment by SciLor** [comment]
You nailed it :D

**Comment by henryk86** [comment]
And click on picture leads to prefiltered Tonies list: 
<img width="480" alt="image" src="https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/f5ee25b6-c798-4603-8bce-d7d12262ba29">

**Comment by henryk86** [comment]
stuff on tonielist still to do

**Comment by henryk86** [comment]
and filter added:
<img width="1025" alt="image" src="https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/7d6e5a2c-05c6-4da4-8e46-ded574654215">
