### ISSUE TITLE
[Enhancement] New /web audio player can be minimized or is only displayed when playing

### ISSUE THREAD

**Issue by oliver-koch** [toniebox-reverse-engineering/teddycloud_web#40]
### [Enhancement] New /web audio player can be minimized or is only displayed when playing

It would be very nice, if the new /web audio player can be minimzed, or is displayed only, when playing a tonie.

**Comment by henryk86** [comment]
You have to keep in mind, that the element must not be closed/reloaded during navigating through teddycloud to keep playing. 
as the header bar is quite full (especially on mobiles)… the side navigation bar has some spare place. But here: how to handle it on mobiles as there is no side navigation.

**Comment by henryk86** [comment]
And before this should be implemented, the player should be finalized as it’s currently a in kind of paused dev version…

**Comment by henryk86** [comment]
In next version, audioplay is hidden if now tonie is started to play.

**Comment by oliver-koch** [comment]
Very nice. Thank you very much!

**Comment by henryk86** [comment]
The player can be also closed. Maybe there is some more optimisation for mobile in nearer future

**Comment by henryk86** [comment]
The change is now in develop. Feel free to have a look

**Comment by henryk86** [comment]
overworked again. can be minimized now:

https://github.com/toniebox-reverse-engineering/teddycloud_web/pull/74#issuecomment-2146861212

**Comment by oliver-koch** [comment]
Looks very nice. I will play with it, and give feedback here.

**Comment by henryk86** [comment]
Merged in develop
