### ISSUE TITLE
Add settings level + internals

### ISSUE THREAD

**Issue by SciLor** [toniebox-reverse-engineering/teddycloud_web#49]
The backend needs to be extended, so every setting gets two additional attributes.

1. Internal or not (show on settings GUI or not)
2. Complexity, Easy or Expert, hide Expert settings by defailt

Frontend and backend work needed.

**Comment by SciLor** [comment]
Backend ready

**Comment by henryk86** [comment]
what are the tasks for frontend?

**Comment by SciLor** [comment]
It would be great to have a level selector on each settings page (toniebox + general)
Could be a selectbox.

**Comment by henryk86** [comment]
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/166761451/6912ca5b-606a-43bf-96aa-f6d25a752b75)
