### ISSUE TITLE
Audioencoder - Dark Mode - Trashcan visual bug

### ISSUE THREAD

**Issue by CTeipen** [toniebox-reverse-engineering/teddycloud_web#57]
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/8715591/a03799fa-6f42-420f-bcfc-6542c97b1bc2)
![image](https://github.com/toniebox-reverse-engineering/teddycloud_web/assets/8715591/9e9c1648-fa7d-41e6-9eae-97fc79ee728c)

**Comment by henryk86** [comment]
bad boy. i will fix it

**Comment by henryk86** [comment]
fix it in gh-58 

btw. you are not using AntD Components there... maybe you should have a look again and do some refactoring
