### ISSUE TITLE
Disable Auto sorting for Audio Encoder  

### ISSUE THREAD

**Issue by j1gg3** [toniebox-reverse-engineering/teddycloud_web#88]
Hi, 
I am currently uploading tons of audio books. So far the encoder works pretty good but I recognized when having more than 10+ files the Encoder website is trying to sort on it's own.  Can this behaviour be turned off? Else I would highly appreciate how to rename my files to get this sorted. 

![image](https://github.com/user-attachments/assets/0b56b04a-2ffb-4a3d-abc5-e8ed64054cbe)

**Comment by henryk86** [comment]
Okay. That’s my change that I added the drag and drop. Will have a look and fix it.

**Comment by SciLor** [comment]
I don't think you can fix that. It is the order the OS presents the files.
A possible solution would be to allow manual sorting of the file list and also by adding a sort by name option.

**Comment by henryk86** [comment]
You can resort the list actually (if this still works… need to check)

**Comment by henryk86** [comment]
there is no autosort as far as i see after a recheck.

the Drag and drop seems to have this behaviour:

the file are sorted as in the Filebrowser. If you drag from the first element, the the first element is the first in the encoder page. if you drag from the 7th element, the 7ths element is the first, then its sorted till the last one and then the first till 6th file.

So the "grab" start position might cause your experience.

Resorting is still working.

I will later check, if i can add a sort by name button

**Comment by henryk86** [comment]
added button sort files alphabetically and also add possibility to create new directories within directory selection:

![image](https://github.com/user-attachments/assets/cb2a264d-da09-4db1-80cc-057d16d76905)

**Comment by henryk86** [comment]
i can confirm now: there is no autosorting. The sort order is equal to the order in the filebrowser.

Only when using the drag and drop functionality, the drag start position marks the first element in the teddycloud list, but again, the order stays the same (besides that the elements above the drag start position are shown at the end of the list.) 

it seems not possible to solve this issue within teddycloud.
