### ISSUE TITLE
Please merge the Web development from teddycloud with Phoniebox

### ISSUE THREAD

**Issue by Mannshoch** [toniebox-reverse-engineering/teddycloud_web#89]
Please merge the Web development from teddycloud with [Phoniebox](https://github.com/MiczFlor/RPi-Jukebox-RFID).

Detach the User experience from the hardware logic and work together.

- Have a pure Media library 
  - where you could upload files 
  - have a sort and inspecting possibility
    - sort by tags like: Album, Interpret, genre
    - sort by attribute like: stream / audio file, podcast, story series (Independent stories)/ history based series (Stories that chapters)/ oneshot, playlist (attached / not attached to device)
    - allow reorganizing playlists 
- have a device Management section
  - Have NFC section where:
    - you see with this device compartible NFC/Tonies
    - see to this device attached NFC/Tonies
    - allow attaching playlists to NFC/Tonies
        (Autogenerate files for toniebox) and have them in a hidden cache as long a media file stays on the server)
- Settings section
  - MQTT / Webhoock / REST API 
  - User Management and Token

See this ticket @ https://github.com/MiczFlor/RPi-Jukebox-RFID/discussions/2415

**Comment by SciLor** [comment]
I don't see synergies. The Toniebox is very special. The backend is optimized for that and needs very special handling for the audio tagging for example.
There won't be much code shared.

**Comment by g3gg0** [comment]
It could share fragments, but as already written,
there would be a lot (too much) custom code for every project.
Every line changed could cause regression test fails on the other.

**Comment by Mannshoch** [comment]
> I don't see synergies. The Toniebox is very special. The backend is optimized for that and needs very special handling for the audio tagging for example. There won't be much code shared.

Not if the whole library works with the original uploaded files and the conversion to the toniebox file format happens the moment a download to the toniebox is needed. 

Currently, the file - as far I assume - is converted as soon I uploaded the file to the teddycloud. But that way, what would happen if the toniebox replaces firmware and modify the way a mediafile have to look like.

The moment you have such boxes you need to manage two different file sets.

An other point may be, that you may not need to develop the library your self and could use one of the already available code.
e.g.: https://medevel.com/music-and-audio-streaming/

**Comment by SciLor** [comment]
> Not if the whole library works with the original uploaded files and the conversion to the toniebox file format happens the moment a download to the toniebox is needed.
This is not possible in a clean way. If you are converting on-the-fly, the file has to be cached afterwards and the box will redownload the file the next time, as there is a checksum at the beginning of the file.

And this is only one specific difference.
